package com.rdude.binancebot.state;

public enum ChatState {

    MAIN_MENU,
    ENTER_SYMBOL_PAIR_GET_AVG_PRICE,
    ENTER_SYMBOL_PAIR_GET_PRICE,
    ENTER_SYMBOL_PAIR_SUBSCRIBE,
    ENTER_CHANGE_PERCENT_SUBSCRIBE

}
